name: DEV - Delete Inf. Stack

on:
  #schedule:
  #  - cron: '0 18 * * 1-5'  # at 18:00 UTC on every day-of-week from Monday through Friday
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: eu-west-1
      
      - name: Delete backend stack
        run: |
          aws cloudformation delete-stack --stack-name BackendStack
          aws cloudformation wait stack-delete-complete --stack-name BackendStack

      - name: Delete database stack
        run: |
          aws cloudformation delete-stack --stack-name DatabaseStack
          aws cloudformation wait stack-delete-complete --stack-name DatabaseStack

  slack-workflow-status:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - Build
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          # Required Input
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          # Optional Input
          channel: '#doct-vetzy-notifications'
          name: 'Doct - Backend'